#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
typedef __u_short u_short; // TODO: fix
#include <fts.h>

#include "grub4dos.h"
#include "utils.h"
#include "../drives.h"
#include "../utils.h"

void write_entry(FILE *f, entry_t *e) {
    fprintf(f, "\n\n");
    fprintf(f, "# %s\n", e->title);
    fprintf(f, "title %s\n", e->title);
    fprintf(f, "\tfind --set-root --ignore-floppies %s", e->initrd);
    fprintf(f, "\tkernel %s %s\n", e->kernel, e->options);
    fprintf(f, "\tinitrd %s\n", e->initrd);
    fprintf(f, "\tboot\n");
}

int regenerate_grub4dos(char *menu_dir) {
    drive_t *win_drive = get_windows_drive();
    char *menu_lst = concat_strs(2, win_drive->path, "\\lick\\menu.lst");

    FILE *menu = fopen(menu_lst, "w");
    fprintf(menu, "This file was generated by LICK.\n");
    fprintf(menu, "DO NOT MODIFY THIS FILE DIRECTLY.");

    node_t *files = get_files(menu_dir);
    for(node_t *n = files; n != NULL; n = n->next) {
        FILE *f = fopen(n->val, "r");
        if(!f)
            continue;
        while(1) {
            entry_t *e = get_entry(f);
            if(e == NULL)
                break;
            write_entry(menu, e);
            free_entry(e);
        }
        fclose(f);
    }

    free_list(files, free);
    free(menu_lst);
    free_drive(win_drive);
    return 1;
}

menu_t get_grub4dos() {
    menu_t menu;
    menu.regenerate = regenerate_grub4dos;
    return menu;
}
